name: .NET CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3 

    - name:  Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x 

    - name:  Restore dependencies
      run: dotnet restore

    - name:  Build
      run: dotnet build --configuration Release --no-restore

    - name:  Run Tests
      run: dotnet test --no-build --verbosity normal

    - name:  Publish App (simuleer deployment)
      run: dotnet publish -c Release -o ./publish

    - name:  Upload published app as artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish
